# Generated by Django 4.2.1 on 2023-09-03 14:43

import backend.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 3, 14, 43, 24, tzinfo=datetime.timezone.utc)),
        ),
    ]
