# Generated by Django 4.2.1 on 2023-09-08 04:31

import backend.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainers',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 8, 4, 31, 5, tzinfo=datetime.timezone.utc)),
        ),
    ]
