# Generated by Django 4.2.1 on 2023-09-08 11:02

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_trainers_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='certificate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 8, 11, 2, 23, tzinfo=datetime.timezone.utc)),
        ),
    ]
