# Generated by Django 4.2.1 on 2023-09-12 04:15

import backend.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_trainers_certificate_alter_useraccount_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 12, 4, 15, 50, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trainers',
            name='catogery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.catogery'),
        ),
    ]
