# Generated by Django 4.2.1 on 2023-09-15 16:47

import backend.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_trainers_t_video_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='t_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers_videos', to='backend.video'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 15, 16, 47, 7, tzinfo=datetime.timezone.utc)),
        ),
    ]
