# Generated by Django 4.2.1 on 2023-09-19 03:43

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_trainers_t_video_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='experience',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trainers',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 19, 3, 43, 45, tzinfo=datetime.timezone.utc)),
        ),
    ]
