# Generated by Django 4.2.1 on 2023-09-24 13:51

import backend.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_trainers_course_fee_alter_useraccount_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 24, 13, 50, 59, tzinfo=datetime.timezone.utc)),
        ),
    ]
