# Generated by Django 4.2.1 on 2023-09-27 09:43

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_appointment_date_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 9, 27, 9, 43, 27, tzinfo=datetime.timezone.utc)),
        ),
    ]
