# Generated by Django 4.2.1 on 2023-10-03 05:24

import backend.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_useraccount_last_login_trainerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerreview',
            name='t_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.trainers'),
        ),
        migrations.AlterField(
            model_name='trainerreview',
            name='t_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 10, 3, 5, 24, 5, tzinfo=datetime.timezone.utc)),
        ),
    ]
