# Generated by Django 4.2.1 on 2023-10-06 04:12

import backend.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_trainerreview_t_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 10, 6, 4, 12, 2, tzinfo=datetime.timezone.utc)),
        ),
    ]
