# Generated by Django 4.2.1 on 2023-10-06 04:58

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 10, 6, 4, 58, 23, tzinfo=datetime.timezone.utc)),
        ),
    ]
