# Generated by Django 4.2.1 on 2023-10-06 05:07

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_subscription_date_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=backend.models.CustomDateTimeField(default=datetime.datetime(2023, 10, 6, 5, 7, 46, tzinfo=datetime.timezone.utc)),
        ),
    ]
